export const GET_TRANSACTIONS = 'GET_TRANSACTIONS'
export const EDIT_TRANSACTION = 'EDIT_TRANSACTION'
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION'
export const ADD_TRANSACTION = 'ADD_TRANSACTION'

export const SHOW_ALERT = 'SHOWALERT'
export const IN_PROGRESS = 'IN_PROGRESS'